name: compile-whole-document

on:
  pull_request:
    types:
      - closed

jobs:
  compile:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: build 
    - name: compiling
      uses: xu-cheng/latex-action@v2
      with:
        root_file: main.tex
        pre_compile: "latexindent -w chapters/*.tex"
        args: "-halt-on-error -interaction=nonstopmode -outdir=./build"
        latexmk_use_lualatex: true
    - name: upload
      uses: actions/upload-artifact@v3
      with:
        name: AAdocs
        path: ./build/
