name: compile-whole-document

on:
  push:
    branches: [ build ]

jobs:
  compile:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: build
    
    - uses: xu-cheng/latex-action@v2
      with:
        root_file: main.tex
        latexmk_use_lualatex: true
        
