name: compile-whole-document

on:
  push:
    branches: [ build ]

jobs:
  compile:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: build
    
    - uses: actions/checkout@v3
      with:
        texlive-version: '2021'
        
    - run: latexindent chapters/*.tex
        
    - run: latexmk -lualatex main.tex
